// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Music_Library.Data;

#nullable disable

namespace Music_Library.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20240117124343_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Music_Library.Models.Album", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ArtistID");

                    b.ToTable("Album", (string)null);
                });

            modelBuilder.Entity("Music_Library.Models.AlbumGenre", b =>
                {
                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.HasKey("AlbumID", "GenreID");

                    b.HasIndex("GenreID");

                    b.ToTable("AlbumGenre", (string)null);
                });

            modelBuilder.Entity("Music_Library.Models.Artist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ArtistID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ArtistID");

                    b.ToTable("Artist", (string)null);
                });

            modelBuilder.Entity("Music_Library.Models.DownloadedAlbum", b =>
                {
                    b.Property<int>("DownloadedAlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DownloadedAlbumID"));

                    b.Property<string>("AlbumID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AlbumID1")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID1")
                        .HasColumnType("int");

                    b.HasKey("DownloadedAlbumID");

                    b.HasIndex("AlbumID1");

                    b.HasIndex("UserID1");

                    b.ToTable("DownloadedAlbum", (string)null);
                });

            modelBuilder.Entity("Music_Library.Models.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("Music_Library.Models.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("Music_Library.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("ReviewID");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Music_Library.Models.Album", b =>
                {
                    b.HasOne("Music_Library.Models.Artist", null)
                        .WithMany("Albums")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Music_Library.Models.AlbumGenre", b =>
                {
                    b.HasOne("Music_Library.Models.Album", "Album")
                        .WithMany("AlbumsGenres")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Music_Library.Models.Genre", "Genre")
                        .WithMany("AlbumGenres")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Music_Library.Models.Artist", b =>
                {
                    b.HasOne("Music_Library.Models.Artist", null)
                        .WithMany("Artists")
                        .HasForeignKey("ArtistID");
                });

            modelBuilder.Entity("Music_Library.Models.DownloadedAlbum", b =>
                {
                    b.HasOne("Music_Library.Models.Album", "Album")
                        .WithMany("DownloadedAlbums")
                        .HasForeignKey("AlbumID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Music_Library.Models.User", "User")
                        .WithMany("DownloadedAlbums")
                        .HasForeignKey("UserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Music_Library.Models.User", b =>
                {
                    b.HasOne("Music_Library.Models.Review", null)
                        .WithMany("Users")
                        .HasForeignKey("ReviewID");
                });

            modelBuilder.Entity("Music_Library.Models.Album", b =>
                {
                    b.Navigation("AlbumsGenres");

                    b.Navigation("DownloadedAlbums");
                });

            modelBuilder.Entity("Music_Library.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Artists");
                });

            modelBuilder.Entity("Music_Library.Models.Genre", b =>
                {
                    b.Navigation("AlbumGenres");
                });

            modelBuilder.Entity("Music_Library.Models.Review", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Music_Library.Models.User", b =>
                {
                    b.Navigation("DownloadedAlbums");
                });
#pragma warning restore 612, 618
        }
    }
}
